### PR TITLE
Fixed issue preventing category exclusion.

### PR DESCRIPTION
**Pull request by ghost**
The previous code is not compatible with 1.0.  This addresses the problem completely.  Please consider republishing this with the fix.

### CODE REVIEW

**Comment by pichalite** [comment]
thanks

**Comment by ghost** [comment]
Hi,

I notice that you took String() away.  The values in the array are strings
of numbers.   If you take that away, it won't work.

Thanks!

On Fri, Jun 24, 2016 at 1:11 PM, Anil Mandepudi notifications@github.com
wrote:

> thanks
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/pichalite/nodebb-plugin-slack-extended/pull/3#issuecomment-228404182,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABn9ofJSdJ1GHrdZSiNXjmSM5dF0_86Jks5qPA-3gaJpZM4I94DS
> .

## 

nofacepress.com

**Comment by pichalite** [comment]
give it a try. let me know if it doesn't work.

**Comment by ghost** [comment]
ok, ill test it on my server and get back to you.

**Comment by ghost** [comment]
Yep, the String() is required or it will never send anything to Slack.

**Comment by pichalite** [comment]
worked for me... tested it using both mongodb & redis

**Comment by ghost** [comment]
What version are you using?  I am on 1.0.3 and it definitely is not working
with that change.

On Fri, Jun 24, 2016 at 1:32 PM, Anil Mandepudi notifications@github.com
wrote:

> worked for me... tested it using both mongodb & redis
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/pichalite/nodebb-plugin-slack-extended/pull/3#issuecomment-228409470,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABn9oXiQGg-JdcF0_jpRBmZDkExwhXRPks5qPBSngaJpZM4I94DS
> .

## 

nofacepress.com

**Comment by pichalite** [comment]
I am on v1.0.3 as well

**Comment by ghost** [comment]
I just make sure, do you have something not selected in channels.  The test
case here is when there are some channels selected, not not all.

On Fri, Jun 24, 2016 at 1:34 PM, Anil Mandepudi notifications@github.com
wrote:

> I am on v1.0.3 as well
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/pichalite/nodebb-plugin-slack-extended/pull/3#issuecomment-228409981,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABn9oYH8vuYfb6toU8Hxo-TZc1_V8AN4ks5qPBUsgaJpZM4I94DS
> .

## 

nofacepress.com

**Comment by pichalite** [comment]
just checked by switching to mongo.. doesn't work... works on redis.

will publish new version.

**Comment by pichalite** [comment]
done

**Comment by ghost** [comment]
Thanks!  This plugin rules!   Maybe down the road it can be extended to
route categories to specific channels.  Not that I need that though.  But
it could.

BTW I wrote another plugin for Slack yesterday to get the user lists.
First one ever for me.
https://github.com/sunsetbrew/nodebb-plugin-slack-extended

Cheers!

On Fri, Jun 24, 2016 at 1:46 PM, Anil Mandepudi notifications@github.com
wrote:

> done
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/pichalite/nodebb-plugin-slack-extended/pull/3#issuecomment-228413138,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABn9obrNYPwEU4Ef7fPgAsAl8JCPgEoPks5qPBfwgaJpZM4I94DS
> .

## 

nofacepress.com

**Comment by ghost** [comment]
Lol, I just noticed I put my fork of your repo in that last message.  That is so funny.   The repo I was talking about is
https://github.com/sunsetbrew/nodebb-widget-slack-users

**Pull request merged**
